/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#include "spi.h"
#include "timer.h"
#include "itron.h"


int main(void){

	timer_init_1ms();
	spi_init();
	vfd_init();

	float lambda = 0.5f;


	while(1){
		for(int i = 0; i<50; i++){
			vfd_display_afr(lambda+((float)i/50));
		}
		for(int i = 50; i>0; i--){
			vfd_display_afr(lambda+((float)i/50));
		}
		//loop forever
	}
}
