/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * 
 * Carson's Paragraph:
 * I learned the hardware implementation of pull resistors, using them to keep
 * my system stable through stm32 reset. additionally i determined the Itron Vfd
 * although very cool, is not very SPI friendly, nor is it 3.3v friendly either.
 * I had to learn about logic level shifter using a part from the TSC. Once
 * that part had been established it was easy enough to set up the display
 * there is a character mode which made writing easy, however i did make a
 * custom function to simplify the work lambda to the symbol for lambda
 * allowing for more space for future graphics is needed. I had a good amount
 * of fun integrating this display into our project and our project being
 * something so useful to the formula team. Additionally i learned what the 6 
 * magic wires are in the wide band o2 sensor
 *
 *
 * Michael's Paragraph:
 * In this lab I learned how a lambda/wideband O2 sensor works and how to
 * control current instead of voltage with the microcontroller. While the high
 * level theory on how the sensor operates was simple to understand, interfacing
 * with the sensor was a challenge. I got to use and now understand the op-amp
 * circuits that were necessary for interfacing with an external peripheral that
 * operates at 12V rather than logic level, and for filtering the pwm outputs.
 * Because of the non-operational state of the vehicle after competition, I was
 * not comfortable testing the sensor outside of the car due to its operating
 * temperature being 1400 degrees F. I instead created a test script that would
 * verify the operation of the hardware. Overall, I had a great time working on
 * this project, using the peripherals we used in class more practically.
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f411xe.h"
#include "AFR_Controller.h"
#include "AFR_test.h"
#include "timer.h"
#include "uart.h"
#include "spi.h"
#include "timer.h"
#include "itron.h"

int main(void){

	systick_init();
	spi_init();
	vfd_init();
	initUsart2();
	AFR_controller_init();
	AFR_Timers_Init();

	while(1){
		vfd_display_afr(get_lambda());
	}
}
